### ISSUE TITLE
ledger-agent OSError: open failed

### ISSUE THREAD

**Issue by Stevus24654** [LedgerHQ/blue-app-ssh-agent#18]
As I tried the great article from Fred de Villamil (https://thoughts.t37.net/a-step-by-step-guide-to-securing-your-ssh-keys-with-the-ledger-nano-s-92e58c64a005), I do not managed to generate the SSH keys (or at least for have a communication with the ledger : 

_$ ledger-agent -c login@host
2018-04-09 21:24:04,844 WARNING      DISPLAY not defined                                                                                  [ui.py:65]
2018-04-09 21:24:04,975 WARNING      error: open failed                                                                                   [server.py:63]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/libagent/server.py", line 58, in handle_connection
    reply = handler.handle(msg=msg)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 205, in parse_public_keys
    for pk in self.public_keys()]
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 199, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/local/lib/python3.6/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python3.6/site-packages/libagent/device/ledger.py", line 47, in connect
    return comm.getDongle()
  File "/usr/local/lib/python3.6/site-packages/ledgerblue/comm.py", line 202, in getDongle
    dev.open_path(hidDevicePath)
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
login@host's password:_

Even with the good password, the connection get closed, and I have no confirmation on the Ledger.
I use the firmware Secure Element 1.4.1 and MCU 1.5 on a High Sierra 10.13.4

**Comment by kroggen** [comment]
After updating the firmware to version 1.6 the USB device id changed from `2c97:0001` to `2c97:1011`. So I had to create an additional line on the udev rules containing the new product id (1011)

Then reload the rules by executing:

```
udevadm trigger
sudo udevadm control --reload-rules
```

**Comment by SpaceComet** [comment]
I think that solves the problem:

```bash
wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash
```

Maybe this issue should be close

**Comment by phuongnd08** [comment]
Just updated ledger firmware recently and this same error start to happen again, add udev rules won't fix.

**Comment by phuongnd08** [comment]
Not sure why, but changing the USB port fix the problem. Both USB ports seem to be working fine (Metamask can use them), but ledgerctl will only works correctly with one port
